### ISSUE TITLE
Order of adding nodes affects resulting mapping

### ISSUE THREAD

**Issue by hpihkala** [andrasq/consistent-hash-js#4]
Hi!

Somewhat similar to #1 and possibly related, I'm trying to achieve deterministic mapping behavior across different instances of `ConsistentHash`. To that end, I already found that the setting `distribution: 'uniform'` creates deterministic results across different runs of the same test cases, which is great. But I also noticed that the insertion order of nodes into the hash ring affects the resulting mapping. Is that expected behavior or a bug? Is there a way to achieve what I want?

Code to reproduce:

```
const ConsistentHash = require('consistent-hash')

const NODES = 10
const RESOURCE = 'foo'

let hr1 = new ConsistentHash({
	distribution: 'uniform'
})

let hr2 = new ConsistentHash({
	distribution: 'uniform'
})

// Add 10 nodes to hr1
for (let i=0; i<NODES; i++) {
	hr1.add(`node-${i}`)
}

// Add the same nodes to hr2 in a different order
for (let i=NODES-1; i>=0; i--) {
	hr2.add(`node-${i}`)
}

console.log(`'${RESOURCE}' maps to ${hr1.get(RESOURCE)} on hr1 and ${hr2.get(RESOURCE)} on hr2`)

// output: 'foo' maps to node-4 on hr1 and node-5 on hr2
```

**Comment by andrasq** [comment]
Hi!

Which nodes get which mappings depends on the order the nodes are added; this is not exactly intentional, but the hash function does not understand nodes, does not examine them and does not order them.  Control points are assigned in node order, and the control points determine the mappings.

One easy workaround might be to externally sort the nodes to ensure that nodes are added in the same order everywhere, which should result in the same mappings seen everywhere.

It might be possible to make the above sort a constructor option; let me think about this.  (The issue is how to cleanly support all 3 types of `add`: random, uniform, and explicit control points.  Should be doable.)

**Comment by hpihkala** [comment]
Hi, thanks for your quick response! Yeah, sorting the nodes in the app before passing them in is exactly what we ended up doing as a workaround, so I can confirm that's valid. 

The inefficiency of that approach might be meaningful in case there are lots of nodes and/or lots of churn, as the library will have to rebuild the whole hash ring every time - so the question becomes this: If that rehashing was built into the library, would a more efficient approach become available than to recompute everything every time? Food for thought and a potential improvement idea. 

I'll go ahead and close this thread, as my issue turned out to be a feature (or a "feature") rather than a bug. :)

**Comment by andrasq** [comment]
Thanks!

Yes, interesting thought.  On first glance it would seem that the library knows less about the nodes i.e. can't be as clever about establishing a deterministic order, but an external "reorderNodes" function could embed that extra knowledge to make them both equally efficient.  For example, if the nodes were read off a global list in the same order everywhere, then sorting would not be necessary and the reorderNodes function could be made a pass-through to capture the application-specific knowledge.
